import json
import os

import numpy as np
import pytest

from stereo_gamma.config import DEFAULT_SENSOR as S
from stereo_gamma.model import StereoModel


def _pinhole_points(model, n, rng):
    """Noise-free correspondences generated by the model itself."""
    uL, vL = rng.uniform(100, S.width - 100, n), rng.uniform(100, S.height - 100, n)
    Z = rng.uniform(0.8, 8.0, n)
    uR, vR = np.empty(n), np.empty(n)
    for i in range(n):
        u, v, _ = model.project_left_point_to_right(uL[i], vL[i], Z[i])
        uR[i], vR[i] = u[0], v[0]
    return uL, vL, uR, vR, Z


@pytest.fixture
def rotated_model(rng):
    m = StereoModel.nominal(S, dx=0.2)
    m.rotation = np.radians([0.2, 1.0, -1.2])
    m.baseline[1] = 0.003
    m.gamma_R = m.gamma_R * (1 + 0.02 * rng.normal(size=m.gamma_R.shape))
    return m


def test_triangulation_inverts_projection(rotated_model, rng):
    uL, vL, uR, vR, Z = _pinhole_points(rotated_model, 50, rng)
    Zp, ok = rotated_model.triangulate(uL, vL, uR, vR)
    assert ok.all()
    assert np.allclose(Zp, Z, rtol=1e-6)


def test_gradient_descent_solver_matches_ols(rotated_model, rng):
    uL, vL, uR, vR, Z = _pinhole_points(rotated_model, 10, rng)
    Z_ols = rotated_model.triangulate(uL, vL, uR, vR)[0]
    Z_gd, iters = rotated_model.triangulate_gd(uL, vL, uR, vR)
    assert np.allclose(Z_gd, Z_ols, rtol=1e-8) and 1 < iters < 20000
    # plain (non-accelerated) GD also converges, just more slowly
    Z_plain, it_plain = rotated_model.triangulate_gd(uL, vL, uR, vR, max_iter=500000,
                                                      tol=1e-9, accelerated=False)
    assert np.allclose(Z_plain, Z_ols, rtol=1e-5) and it_plain > iters


def test_right_to_left_projection_is_consistent(rotated_model):
    uL, vL, Z = 900.0, 700.0, 3.0
    uR, vR, _ = rotated_model.project_left_point_to_right(uL, vL, Z)
    bu, bv = rotated_model.epipolar_curve_left(uR[0], vR[0], n=4000)
    assert np.min(np.hypot(bu - uL, bv - vL)) < 1.0


def test_invalid_geometry_returns_nan():
    m = StereoModel.nominal(S, dx=0.2)
    Z, ok = m.triangulate([1000.0], [900.0], [1100.0], [900.0])  # negative disparity
    assert not ok[0] and np.isnan(Z[0])


def test_uncertainty_grows_with_depth(rotated_model, rng):
    rotated_model.meta.update(sigma_px=1.0, rel_model_error=0.0)
    sig = []
    for Z in (1.0, 4.0):
        uR, vR, _ = rotated_model.project_left_point_to_right(1296.0, 972.0, Z)
        z, s_tot, s_click = rotated_model.depth_uncertainty(1296.0, 972.0, uR[0], vR[0])
        assert np.isclose(z, Z, rtol=1e-6) and np.isclose(s_tot, s_click)
        sig.append(s_tot)
    # stereo depth error grows ~ Z²
    assert 10 < sig[1] / sig[0] < 22


def test_save_load_roundtrip(tmp_path, rotated_model):
    rotated_model.postcorr = np.array([0.01, 0.98, 0.002])
    rotated_model.meta["note"] = "x"
    p = tmp_path / "c.json"
    rotated_model.save(p)
    m2 = StereoModel.load(p)
    for a in ("gamma_L", "gamma_R", "baseline", "rotation", "postcorr"):
        assert np.allclose(getattr(m2, a), getattr(rotated_model, a))
    assert m2.meta["note"] == "x" and m2.sensor == rotated_model.sensor


def test_postcorrection_inverse():
    m = StereoModel.nominal(S)
    m.postcorr = np.array([0.05, 0.9, 0.01])
    Z = np.array([0.7, 2.0, 5.0])
    assert np.allclose(m.apply_postcorr(m.raw_depth_for(Z)), Z, rtol=1e-4)


def test_loads_v1_calibration_and_reproduces_it(root, real_points):
    """The v1 file format (single γ grid, key 'gamma_L_4x4') still loads and gives v1 depths."""
    path = os.path.join(root, "data", "calibration_v1_legacy.json")
    m = StereoModel.load(path)
    p = json.load(open(path))
    G = np.asarray(p["gamma_L_4x4"])
    assert np.allclose(m.gamma_L[..., 0], G) and np.allclose(m.gamma_L[..., 1], G)
    Z = m.triangulate(*real_points[:, :4].T)[0]
    assert np.nanmean(np.abs(Z / real_points[:, 4] - 1)) == pytest.approx(0.0346, abs=5e-4)


def test_v1_4x4_grid_is_upsampled():
    g = np.full((4, 4), 0.45)
    m = StereoModel.from_dict({"gamma_L_4x4": g.tolist(), "gamma_R_4x4": g.tolist(),
                               "baseline": {"dx": 0.2, "dy": 0.0}})
    assert m.gamma_L.shape == (5, 5, 2) and np.allclose(m.gamma_L, 0.45)


def test_empty_calibration_file_raises(tmp_path):
    p = tmp_path / "e.json"
    p.write_text("  ")
    with pytest.raises(ValueError):
        StereoModel.load(p)
